name: udemy_curso_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_launcher_icons: ^0.14.3
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_ui_auth: ^1.16.1
  intl: ^0.19.0
  firebase_ui_localizations: ^1.13.1
  image_picker: ^1.1.2
  another_flutter_splash_screen: ^1.2.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  get_storage: ^2.1.1
  simple_circular_progress_bar: ^1.0.2
  uuid: ^4.5.1
  cloud_firestore: ^5.6.2
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dog.png"
  min_sdk_android: 21
  color: ""
  web:
    generate: true
    image_path: "assets/images/dog.png"


  windows:
    generate: true
    image_path: "assets/images/dog.png"
    icon_size: 48


  macos:
    generate: true
    image_path: "assets/images/dog.png"


  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

